export const districts = [
    { label: "Ancón", value: "Ancon" },
    { label: "Ate", value: "Ate" },
    { label: "Barranco", value: "Barranco" },
    { label: "Breña", value: "Brena" },
    { label: "Carabayllo", value: "Carabayllo" },
    { label: "Chaclacayo", value: "Chaclacayo" },
    { label: "Chorrillos", value: "Chorrillos" },
    { label: "Cieneguilla", value: "Cieneguilla" },
    { label: "Comas", value: "Comas" },
    { label: "El Agustino", value: "El Agustino" },
    { label: "Independencia", value: "Independencia" },
    { label: "Jesús María", value: "Jesus Maria" },
    { label: "La Molina", value: "La Molina" },
    { label: "La Victoria", value: "La Victoria" },
    { label: "Lima", value: "Lima" },
    { label: "Lince", value: "Lince" },
    { label: "Los Olivos", value: "Los Olivos" },
    { label: "Lurigancho", value: "Lurigancho" },
    { label: "Lurín", value: "Lurin" },
    { label: "Magdalena del Mar", value: "Magdalena del Mar" },
    { label: "Miraflores", value: "Miraflores" },
    { label: "Pachacámac", value: "Pachacamac" },
    { label: "Pucusana", value: "Pucusana" },
    { label: "Pueblo Libre", value: "Pueblo Libre" },
    { label: "Puente Piedra", value: "Puente Piedra" },
    { label: "Punta Hermosa", value: "Punta Hermosa" },
    { label: "Punta Negra", value: "Punta Negra" },
    { label: "Rímac", value: "Rimac" },
    { label: "San Bartolo", value: "San Bartolo" },
    { label: "San Borja", value: "San Borja" },
    { label: "San Isidro", value: "San Isidro" },
    { label: "San Juan de Lurigancho", value: "San Juan de Lurigancho" },
    { label: "San Juan de Miraflores", value: "San Juan de Miraflores" },
    { label: "San Luis", value: "San Luis" },
    { label: "San Martín de Porres", value: "San Martin de Porres" },
    { label: "San Miguel", value: "San Miguel" },
    { label: "Santa Anita", value: "Santa Anita" },
    { label: "Santa María del Mar", value: "Santa Maria del Mar" },
    { label: "Santa Rosa", value: "Santa Rosa" },
    { label: "Santiago de Surco", value: "Santiago de Surco" },
    { label: "Surquillo", value: "Surquillo" },
    { label: "Villa El Salvador", value: "Villa El Salvador" },
    { label: "Villa María del Triunfo", value: "Villa Maria del Triunfo" }
];
